### PR TITLE
TOC updates

### PR DESCRIPTION
**Pull request by rluxemburg**
# Pull request

## Summary of Changes
- Updated TOC per Christopher's submitted XLS in [DEVEP-760](https://jira.corp.adobe.com/browse/DEVEP-760)

## What kind of change does this PR introduce? 
- [X] Enhancement (_Added nested links to TOC_)

### CODE REVIEW

**Comment by slaanesh** [comment]
the branch needs to be rebased @rluxemburg

**Comment by rluxemburg** [comment]
resubmitted

**Comment by slaanesh** [comment]
i don't think so, there's still a conflit @rluxemburg

**Comment by rluxemburg** [comment]
Please check PR #17 instead and ignore this one.

**Pull request closed without merging**
